'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")>  _
Partial Friend NotInheritable Class Configuracion
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Configuracion = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Configuracion()),Configuracion)
    
    Public Shared ReadOnly Property [Default]() As Configuracion
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Correo() As String
        Get
            Return CType(Me("Correo"),String)
        End Get
        Set
            Me("Correo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ServidorSalidaCorreo() As String
        Get
            Return CType(Me("ServidorSalidaCorreo"),String)
        End Get
        Set
            Me("ServidorSalidaCorreo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property PuertoCorreo() As String
        Get
            Return CType(Me("PuertoCorreo"),String)
        End Get
        Set
            Me("PuertoCorreo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property UsaSSL() As Boolean
        Get
            Return CType(Me("UsaSSL"),Boolean)
        End Get
        Set
            Me("UsaSSL") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Servidor() As String
        Get
            Return CType(Me("Servidor"),String)
        End Get
        Set
            Me("Servidor") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property BaseDeDatos() As String
        Get
            Return CType(Me("BaseDeDatos"),String)
        End Get
        Set
            Me("BaseDeDatos") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property UltimoUsuario() As String
        Get
            Return CType(Me("UltimoUsuario"),String)
        End Get
        Set
            Me("UltimoUsuario") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property ContrasenaCorreo() As String
        Get
            Return CType(Me("ContrasenaCorreo"),String)
        End Get
        Set
            Me("ContrasenaCorreo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property noSucursal() As String
        Get
            Return CType(Me("noSucursal"),String)
        End Get
        Set
            Me("noSucursal") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property FuncionPortal() As Boolean
        Get
            Return CType(Me("FuncionPortal"),Boolean)
        End Get
        Set
            Me("FuncionPortal") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Sender() As String
        Get
            Return CType(Me("Sender"),String)
        End Get
        Set
            Me("Sender") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Configuration.DefaultSettingValueAttribute("")>
    Public Property Etiqueta() As String
        Get
            Return CType(Me("Etiqueta"), String)
        End Get
        Set
            Me("Etiqueta") = Value
        End Set
    End Property
End Class
